python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Readable\Buse_Top"
python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Readable\Dorn_Top"
python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Readable\Scalabrino_Top"
python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Unreadable\Buse_Bottom"
python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Unreadable\Dorn_Bottom"
python matrix.py --input_dir="W:\OneDrive\shared\Matrix\Code Snippet Repository\Unreadable\Scalabrino_Bottom"